### ISSUE TITLE
[BUG/Feature]: show pages and contentTypes by language/filterable by sys-languag

### ISSUE THREAD

**Issue by fgerards** [agence-gaya/typo3-content-usage#1]
it seems that the backend module shows pages/doktypes with sys_language_uid = 0 even if they are >0. The same is true for CType instances. Can we get a dropdown to filter by language ? or correct language-flag at the entry ?

**Comment by b3nkai** [comment]
Hi Frank,

Thanks for your issue and sorry for the delay of my response !
I'll take a look as soon as I can and let you know.

Ben

**Comment by b3nkai** [comment]
The display of language and workspace uids is fixed and backported on all versions.

Concerning the filters, this will be treated in another issue ( #8 ). This will take a little more time, especially for backport on all versions.
